### ISSUE TITLE
Maven package not found for latest versions

### ISSUE THREAD

**Issue by Jiazheng411** [Lonzak/JPedal#2]
Hi, it seems that the latest version of Jpedal-lgpl(version 4.92) cannot be found, even there is a maven repository page here https://mvnrepository.com/artifact/org.jpedal/jpedal-lgpl/4.92b23, but the files cannot be access, and there are no jars under http://maven.icm.edu.pl/artifactory/repo/org/jpedal May I know where to find the latest version?

**Comment by Lonzak** [comment]
The latest release (mine) is available https://github.com/Lonzak/JPedal/tree/master/dist however I do not release to maven central. On mvnrepo the following external repo is linked:
https://software.rescarta.org/nexus/content/repositories/thirdparty/org/jpedal/jpedal-lgpl/jpedal-lgpl/4.92b23/
